# NLP

In [14]:
import nltk
import re
import pandas as pd

In [5]:
from nltk.stem import WordNetLemmatizer

In [8]:
lemma=WordNetLemmatizer()

In [6]:
sentences=nltk.sent_tokenize(comment)

In [7]:
from nltk.corpus import stopwords

In [30]:
corpus=[]

In [18]:
comment=pd.read_csv("C:\\Users\\Kedar-PC\\Desktop\\Dataset\\SMSSpamCollection",sep='\t',names=['label','message'])

In [19]:
comment

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [31]:
for i in range(len(comment)):
    review=re.sub('[^a-z A-Z 0-9]',' ',comment['message'][i])
    review=review.lower()
    review=review.split()
    review=[lemma.lemmatize(i) for i in review if not i in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)


In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [53]:
tf=TfidfVectorizer(max_features=5000)

In [54]:
pd.pandas.set_option('display.max_columns',None)

In [55]:
x=tf.fit_transform(corpus).toarray()

In [56]:
x.shape

(5572, 5000)

In [65]:
y=pd.get_dummies(comment['label'],drop_first=True)

In [67]:
y=y.iloc[:,0].values

In [68]:
y

array([0, 0, 1, ..., 0, 0, 0], dtype=uint8)

In [69]:
from sklearn.model_selection import train_test_split

In [70]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [71]:
from sklearn.naive_bayes import MultinomialNB


In [72]:
spam_detect_model=MultinomialNB().fit(x_train,y_train)

In [73]:
y_pred=spam_detect_model.predict(x_test)

In [74]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [76]:
from sklearn.metrics import confusion_matrix

In [77]:
cm=confusion_matrix(y_test,y_pred)

In [78]:
cm

array([[1451,    0],
       [  36,  185]], dtype=int64)

In [79]:
from sklearn.metrics import accuracy_score

In [80]:
ac=accuracy_score(y_test,y_pred)

In [81]:
ac

0.9784688995215312